Channel: "5891096865:AAFHsDFzfFfgFDBDIUe5drg68OKsDOu9HUw"
ChatID: "-1001809111657"
Blaze: "https://blaze.com/api/roulette_games/history"
API_HASH: "cb31e372739a3e1b051fdfb4ef4b68f4"
API_ID: 21387580
CHANNEL_LINK: "https://t.me/+q1XawVBl-YowNzhh"
MODEL_PATH: forest.sav
WEBSOCKET: "wss://api-v2.blaze.com/replication/?EIO=3&transport=websocket"
LOGS: "logs/requests.log"
JOIN: '423["cmd",{"id":"subscribe","payload":{"room":"double_v2"}}]'
